[dev]
framework = "#static"

[build]
command = "echo No build for this site, we are living on the edge"
publish = "public"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."


[[redirects]]
from = "/redirect_test"
to = "https://google.com"
status = 200

[[edge_functions]]
  function = "fetch"
  path = "/*"